#!/bin/sh

set -e -u

rsync -a --delete options/x11-options/ /var/db/ports/
chown -R root:wheel /var/db/ports/

rm -r -f -v /usr/local/etc/poudriere.d/*blacklist
rm -r -f -v /usr/local/etc/poudriere.d/*make.conf
rm -r -f -v /usr/local/etc/poudriere.d/*poudriere.conf
rm -r -f -v /usr/local/etc/poudriere.d/*options

install -o root -g wheel -m 644 -v env/*make.conf /usr/local/etc/poudriere.d/
install -o root -g wheel -m 644 -v env/*poudriere.conf /usr/local/etc/poudriere.d/
install -o root -g wheel -m 644 -v blacklist/*blacklist /usr/local/etc/poudriere.d/

rsync -a --delete options/*options /usr/local/etc/poudriere.d/
