#!/bin/sh

set -e -u

: ${ORIGIN:=}

while getopts "o:" OPT; do
    case $OPT in
        o)
            ORIGIN=${OPTARG}
            ;;
    esac
done

shift $((${OPTIND} - 1))

[ -n "${ORIGIN}" ] || {
    echo "$(basename $0): origin not specified."
    exit 1
}

for _file in "$@"; do
    [ -f ${_file} ] || {
        echo "$(basename $0): ${_file} does not exist."
        exit 1
    }
done

_lastfile=""

for _file in "$@"; do
    _lastfile=${_file}

    echo "$(basename $0): removing ${ORIGIN} from ${_file}."

    _target=$(echo ${ORIGIN} | sed -e 's/\//\\\//g')

    sed -i '' -e "/^${_target}$/d" ${_file}

    git add ${_file}
done

git commit -m "$(basename $(dirname ${_lastfile})): remove ${ORIGIN}."
